language: go

sudo: false

go:
  - 1.8

install:
 - go get -u github.com/mattn/goveralls

script:
  - GOMAXPROCS=1 go test -timeout 30s ./...
  - GOMAXPROCS=4 go test -timeout 30s -race ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN